package message

import (
	"fmt"

	"github.com/noPerfection/datatype"
)

// RequestInterface generic requests
type RequestInterface interface {
	// ConId returns a connection id for each sending session.
	ConId() string
	SetConId(string)
	// String implements the Stringer interface from a standard library
	String() string
	// ZmqEnvelope converts the message to the zeromq envelope
	ZmqEnvelope() ([]string, error)
	// Fail creates a new Reply as a failure
	// It accepts the error message that explains the reason of the failure.
	Fail(message string) ReplyInterface
	Ok(parameters datatype.KeyValue) ReplyInterface
	CommandName() string
	RouteParameters() datatype.KeyValue
}

var _ RequestInterface = (*Request)(nil)

}

// Request message sent by Client socket and accepted by ControllerCategory socket.
type Request struct {
	Command    string            `json:"command"`
	Parameters datatype.KeyValue `json:"parameters"`
	conId      string            // This one is used between sockets, generated by sockets
}

// CommandName returns a command name
func (request *Request) CommandName() string {
	return request.Command
}

// RouteParameters returns a command name
func (request *Request) RouteParameters() datatype.KeyValue {
	return request.Parameters
}

// ConId returns a connection id for each sending session.
func (request *Request) ConId() string {
	return request.conId
}

func (request *Request) SetConId(conId string) {
	request.conId = conId
}

// String returns the message body.
func (request *Request) String() string {
	kv, err := datatype.NewFromInterface(request)
	if err != nil {
		return ""
	}

	bytes, err := kv.Bytes()
	if err != nil {
		return ""
	}

	return string(bytes)
}

func (request *Request) ZmqEnvelope() ([]string, error) {
	str := request.String()
	if str == "" {
		return nil, fmt.Errorf("request.String returned an empty string")
	}

	if len(request.conId) > 0 {
		return []string{request.conId, "", str}, nil
	}

	return []string{"", str}, nil
}

// Fail creates a new Reply as a failure
// It accepts the error message that explains the reason of the failure.
func (request *Request) Fail(message string) ReplyInterface {
	reply := &Reply{
		Status:     FAIL,
		Message:    message,
		Parameters: datatype.New(),
		conId:      request.conId,
	}

	return reply
}

func (request *Request) Ok(parameters datatype.KeyValue) ReplyInterface {
	reply := &Reply{
		Status:     OK,
		Message:    "",
		Parameters: parameters,
		conId:      request.conId,
	}

	return reply
}
