package message

import (
	"fmt"

	"github.com/noPerfection/datatype"
)

var _ RequestInterface = (*Request)(nil)

// DefaultMessage returns a message for parsing request and parsing reply.
func DefaultMessage() *Operations {
	return &Operations{
		Name:       "default",
		NewReq:     NewReq,
		NewReply:   NewRep,
		EmptyReq:   NewEmptyReq,
		EmptyReply: NewEmptyReply,
	}
}

func NewEmptyReq() RequestInterface {
	return &Request{}
}

// NewReq from the zeromq messages
func NewReq(messages []string) (RequestInterface, error) {
	msg := JoinMessages(messages)

	data, err := datatype.NewFromString(msg)
	if err != nil {
		return nil, fmt.Errorf("failed to convert message string %s to key-value: %v", msg, err)
	}

	var request Request
	err = data.Interface(&request)
	if err != nil {
		return nil, fmt.Errorf("failed to convert key-value %v to intermediate interface: %v", data, err)
	}

	// verify that data is not nil
	if request.String() == "" {
		return nil, fmt.Errorf("failed to validate")
	}

	if MultiPart(messages) {
		request.conId = messages[0]
	}

	return &request, nil
}

// Request message sent by Client socket and accepted by ControllerCategory socket.
type Request struct {
	Trace      []*Stack          `json:"traces,omitempty"`
	Command    string            `json:"command"`
	Parameters datatype.KeyValue `json:"parameters"`
	conId      string            // This one is used between sockets, generated by sockets
}

// CommandName returns a command name
func (request *Request) CommandName() string {
	return request.Command
}

// RouteParameters returns a command name
func (request *Request) RouteParameters() datatype.KeyValue {
	return request.Parameters
}

// ConId returns a connection id for each sending session.
func (request *Request) ConId() string {
	return request.conId
}

func (request *Request) SetConId(conId string) {
	request.conId = conId
}

// JoinMessages the message
func (request *Request) String() string {
	err := ValidCommand(request.Command)
	if err != nil {
		return ""
	}

	kv, err := datatype.NewFromInterface(request)
	if err != nil {
		return ""
	}

	bytes, err := kv.Bytes()
	if err != nil {
		return ""
	}

	return string(bytes)
}

func (request *Request) ZmqEnvelope() ([]string, error) {
	str := request.String()
	if str == "" {
		return nil, fmt.Errorf("request.String returned an empty string")
	}

	if len(request.conId) > 0 {
		return []string{request.conId, "", str}, nil
	}

	return []string{"", str}, nil
}

// Fail creates a new Reply as a failure
// It accepts the error message that explains the reason of the failure.
func (request *Request) Fail(message string) ReplyInterface {
	reply := &Reply{
		Status:     FAIL,
		Message:    message,
		Parameters: datatype.New(),
		conId:      request.conId,
		Trace:      request.Trace,
	}

	return reply
}

func (request *Request) Ok(parameters datatype.KeyValue) ReplyInterface {
	reply := &Reply{
		Status:     OK,
		Message:    "",
		Parameters: parameters,
		Trace:      request.Trace,
		conId:      request.conId,
	}

	return reply
}
